---
- name: Update cache for planet
  hosts: planet
  gather_facts: no
  strategy: free
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role: apigee-opdk-setup-default-settings, tags: ['cache'] }

- name: Recover a cassandra node that is reported dead
  hosts: '{{ hosts }}'
  serial: 1
  gather_facts: no
  roles:
  - { role: apigee-opdk-cassandra-deadnode-recovery-config, tags: ['config'] }
  - { role: apigee-opdk-stop-components, component_name: 'apigee-cassandra', tags: ['stop', 'restart']}
  - { role: apigee-opdk-start-components, component_name: 'apigee-cassandra', tags: ['start', 'restart'] }
  - { role: apigee-opdk-cassandra-deadnode-recovery-complete, tags: ['complete'] }
  - { role: apigee-opdk-cassandra-rebuild, tags: ['rebuild'] }

- name: Download logs and configs from dc-1-ds
  include: opdk-setup-log-files.yml
  vars:
    hosts: "{{ hosts }}"
  tags: ['logs']
